# Generated by Django 4.2.6 on 2023-10-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='links',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=501),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.JSONField(null=True),
        ),
    ]
