# Generated by Django 4.2.6 on 2023-10-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_post_comments_alter_post_likes_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
