# Generated by Django 4.2.6 on 2023-10-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_comment_likes_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='upvotes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='upvotes',
        ),
    ]
